spring:
  ai:
    mcp:
      server:
        protocol: STATELESS
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9000/realms/master
          jwk-set-uri: http://localhost:9000/realms/master/protocol/openid-connect/certs
          audiences: learning-mcp-with-spring-ai
